name: CI
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install npm packages
        working-directory: ./billsplit
        run: npm i
        
      - name: Install Angular CLI
        run: sudo npm i -g @angular/cli@10.1.3 > /dev/null
  
      - name: Build for production
        working-directory: ./billsplit
        run: ng build --configuration production --base-href /billsplit/
      
      - name: Deploy to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'billsplit/dist/billsplit'
          destination_dir: 'billsplit'
